martincostello/browserstack-automate

- src/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientExtensionsTests.cs
- src/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- src/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
- src/MartinCostello.BrowserStack.Automate.Tests/packages.config
Use [FluentAssertions](https://github.com/dennisdoomen/FluentAssertions) for assertions in the tests instead of the [xUnit](https://github.com/xunit/xunit) ```Assert``` class.
> Use FluentAssertions in tests

- README.md
Add Travis build badge and chart.
> Add Travis badge and chart

- README.md
Clarify the support for .NET Core by stating the version of .NET Standard.
> Clarify .NET Core support

- .azure-pipelines/build-template.yml
Make BrowserStack Automate secrets available to build scripts for use with tests.
> Configure BrowserStack Automate secrets for Azure Pipelines

- .azure-pipelines/build-template.yml
- Build.ps1
- Directory.Build.props
- appveyor.yml
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
* Fix test failing if the project list becomes "old" and has no entries.
* Update ReportGenerator (replaces #63).
* Use coverlet instead of OpenCover.
> Fix CI and switch to coverlet

- Build.ps1
- Directory.Build.props
- global.json
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
* Update tests to target .NET Core 3.1.3.
* Update coverlet.msbuild.
> Update to .NET Core 3.1.3

- Directory.Build.props
Bump version to 3.0.2 as 3.0.1 shipped some time ago.
> Bump version to 3.0.2

- .vscode/extensions.json
- Directory.Build.props
- Directory.Packages.props
- MartinCostello.BrowserStack.Automate.sln
- build.ps1
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
* Enable central management of NuGet package versions.
* Add configuration file for suggestion Visual Studio Code extensions.
> Manage NuGet packages centrally

- .github/workflows/update-dotnet-sdk.yml
- .vsconfig
- Directory.Packages.props
- global.json
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Update to use the .NET 5 SDK to build and test the library.
> Update to .NET 5 SDK

- Directory.Build.props
Bump package version to 3.0.3 for next release.
> Bump version to 3.0.3

- Directory.Build.targets
- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/AutomatePlanStatus.cs
- src/MartinCostello.BrowserStack.Automate/Browser.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClientExtensions.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateError.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateException.cs
- src/MartinCostello.BrowserStack.Automate/Build.cs
- src/MartinCostello.BrowserStack.Automate/BuildDetail.cs
- src/MartinCostello.BrowserStack.Automate/Project.cs
- src/MartinCostello.BrowserStack.Automate/ProjectDetail.cs
- src/MartinCostello.BrowserStack.Automate/ProjectDetailItem.cs
- src/MartinCostello.BrowserStack.Automate/RecycleAccessKeyResult.cs
- src/MartinCostello.BrowserStack.Automate/Session.cs
- src/MartinCostello.BrowserStack.Automate/SessionDetail.cs
- stylecop.json
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientExtensionsTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/RequiresServiceCredentialsFactAttribute.cs
Move using statements to outside the namespace so that global usings could be used.
Also some coverlet improvements.
> Move usings

- .vsconfig
- Directory.Packages.props
- MartinCostello.BrowserStack.Automate.sln
- global.json
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
> Update to .NET 6

- Directory.Packages.props
- build.ps1
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Add GitHubActionsTestLogger for use with dotnet test.
> Add GitHubActionsTestLogger

- .vsconfig
- Directory.Packages.props
- global.json
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
> Update to .NET 7

- .github/workflows/update-dotnet-sdk.yml
Pin the version to a SHA to resolve OSSF warning.
> Pin action version

- build.ps1
Remove unused function missed from #428.
> Remove unused function

- .github/workflows/build.yml
Disable publishing to MyGet until it comes back online.
> Disable MyGet publishing

- Directory.Packages.props
Remove unused reference to Moq.
> Remove unused Moq reference

- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
Bump StyleCop.Analyzers to latest pre-release that supports modern C# features.
> Bump StyleCop.Analyzers

- .github/dependabot.yml
- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
Use the `VersionOverride` property instead of MSBuild conditions.
> Use VersionOverride

- Directory.Build.props
- README.md
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- Bump version to 4.0.1 for next release.
- Enable package validation.
- Make sample in README valid for nullable reference types and fix incorrect comment.
> Bump version

- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
The override should not have been changed.
> Revert package bump

- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
> Revert package update

- CODE_OF_CONDUCT.md
- Directory.Build.props
- LICENSE
- README.md
- package-readme.md
Add a dedicated package README to improve rendering in the NuGet gallery.
> Add dedicated package README

- .github/dependabot.yml
- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
Fix-up the pinned version of System.Text.Json and ignore from future dependabot updates.
> Fix System.Text.Json version

- .editorconfig
- Directory.Build.props
- Directory.Packages.props
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
- Enable (almost) all built-in style analyzers.
- Use global package references.
- Add reference trimmer analyzer.
> Solution improvements

- .github/workflows/build.yml
Fix binaries not being attested.
> Fix attestation

- .github/update-dotnet-sdk.json
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- Fix package version that should not have been updated.
- Disable .NET SDK updates from bumping NuGet packages.
> Fix package version

- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClientExtensions.cs
Use `#if NET` rather than including the version.
> Simplify pre-processor conditions

- build.ps1
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Disable JSON reflection in tests to validate AoT compatibility.
> Disable JSON reflection

- package-readme.md
Add a NuGet badge for downloads.
> Add downloads badge

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/lint.yml
- .markdownlint.json
> Add markdownlint

- Directory.Packages.props
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientExtensionsTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Migrate the tests to xunit v3.
> Migrate to xunit v3

- .github/workflows/build.yml
- Directory.Packages.props
- build.ps1
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Use Codecov's test analytics feature.
> Add test analytics

- .github/workflows/codeql.yml
- MartinCostello.BrowserStack.Automate.slnx
Extend CodeQL analysis to include GitHub Actions.
> Extend CodeQL

- Directory.Build.props
- Directory.Packages.props
- global.json
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
Update to preview 6 of .NET Core 10.
> Update to .NET Core 10 preview 6
