- src/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
Fix broken integration test by allowing sessions to be empty for a build (as the build might indeed have no sessions).
> Fix broken integration test

- appveyor.yml
- src/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- src/MartinCostello.BrowserStack.Automate/AutomatePlanStatus.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateError.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateException.cs
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- src/MartinCostello.BrowserStack.Automate/SessionDetail.cs
* Add support for new API resources:
1. ```DELETE projects/<project-id>.json```
1. ```DELETE builds/<build-id>.json```
1. ```DELETE sessions/<session-id>.json```
1. ```GET builds/<build-id>/sessions/<session-id>/logs.json```
* Add new object properties:
1. ```public_url``` as ```PublicUri``` to ```SessionDetail```
1. ```team_parallel_sessions_max_allowed``` as ```TeamMaximumAllowedParallelSessions``` to ```AutomatePlanStatus```
* Throw ```BrowserStackAutomateException``` if a HTTP 404 occurs when invoking a method on the client.
> Add new API resources

- README.md
- src/.nuget/packages.config
- src/MartinCostello.BrowserStack.Automate.msbuild
Remove codecov.io and OpenCover as they do not yet support .NET Core.
> Remove codecov.io and OpenCover

- appveyor.yml
Remove the AppVeyor branch restriction as it is stopping builds for tags.
> Remove AppVeyor branch restriction

- src/MartinCostello.BrowserStack.Automate/project.json
- tests/MartinCostello.BrowserStack.Automate.Tests/project.json
Fix typo in the project URL that creates a 404 in the [NuGet package listing](https://www.nuget.org/packages/MartinCostello.BrowserStack.Automate/2.0.0).
> Fix typo in project URL

- src/MartinCostello.BrowserStack.Automate/project.json
Fix "BrowserStack" appearing twice as a tag in the NuGet package.
> Fix duplicate NuGet package tag

- .travis.yml
- build.sh
Improve build time for Travis CI by not using an image that installs Mono.
> Improve Travis CI build time

- Directory.Build.props
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClientExtensions.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateError.cs
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
* Support injection of `HttpClient` for interop with [HttpClientFactory](https://github.com/aspnet/HttpClientFactory).
* Add support for usage of `CancellationToken`.
* Use `ConfigureAwait(false)` for awaitable calls.
> HttpClientFactory Interop

- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClientExtensions.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
* Expose new BrowserStack Automate API functionality:
* Rename builds, projects and sessions.
* Delete multiple builds and sessions.
* Get Appium, Console and Network logs.
* Support `offset` query string parameter for pagination.
* Update BrowserStack Automate API base URI.
* Add more `CancellationToken` parameters.
* Fix incorrect XML documentation.
> Add new methods

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
- .gitignore
- Build.ps1
- CODE_OF_CONDUCT.md
- Directory.Build.props
- LICENSE
- MartinCostello.BrowserStack.Automate.sln
- appveyor.yml
1. Update code analyzers to `2.6.2`.
1. Add GitHub community documentation.
1. Update NuGet API key.
1. Remove boilerplate from `LICENSE`.
> Update analyzers and Community docs

- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- src/MartinCostello.BrowserStack.Automate/Session.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
Looks like some things were missed from #21, and some parts were incompatible with the BrowserStack Automate API. Specifically:
1. Builds and sessions are returned in a wrapper object.
1. The duration of a session can be null.
To keep this fix as a patch release, rather than a `4.0.0`, `Session` is updated to ignore nulls, and the wrapper objects are deserialized internally and unwrapped so that the return types of `BrowserStackAutomateClient` are the same.
> Fix schema

- Directory.Build.props
Use new symbol package format for NuGet.
> Use new symbol package format

- Directory.Packages.props
Update NuGet packages to latest versions for .NET 5.0.1.
> Update NuGet packages for .NET 5.0.1

- src/MartinCostello.BrowserStack.Automate/AutomatePlanStatus.cs
- src/MartinCostello.BrowserStack.Automate/Build.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
The BrowserStack API appears to returning `null` rather than 0 for a selection of properties. This changes to the null handling of a few of the properties to "Ignore" to avoid any breaking changes.
> Handle null as 0 for a few properties

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/launch.json
- Directory.Packages.props
- build.ps1
* Add support for GitHub Codespaces.
* Use the `NUGET_PACKAGES` environment variables for the NuGet package cache location if it is set.
* Only add a package references for `ReportGenerator` for test projects.
> Codespaces

- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/BrowserStackAutomateClient.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientExtensionsTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/BrowserStackAutomateClientTests.cs
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
*  Remove FluentAssertions due to v6 breaking changes and replace with Shouldly. Replaces #261.
* Address Visual Studio refactoring suggestions and use simplified using statements and target-typed new expressions.
> Remove FluentAssertions

- Directory.Packages.props
Revert the Newtonsoft.Json version used in the library.
> Revert baseline version

- Directory.Packages.props
Revert the version of Newtonsoft.Json for the library.
> Revert baseline Newtonsoft.Json version

- Directory.Build.props
- Directory.Packages.props
- Bump Newtonsoft.Json to 13.0.1 to resolve GHSA-5crp-9r3c-p9vr.
- Bump version to 4.0.0.
> Bump Newtonsoft.Json to 13.0.1

- README.md
Make the link to the NuGet package HTTPS.
> Use HTTPS for NuGet badge

- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- tests/MartinCostello.BrowserStack.Automate.Tests/MartinCostello.BrowserStack.Automate.Tests.csproj
Fix Microsoft.CodeAnalysis.PublicApiAnalyzers being incorrectly included as a dependency of projects consuming the package.
> Fix dependency

- README.md
Add `using` to code sample to avoid CA2000 warning.
> Dispose of client

- .github/dependabot.yml
- Directory.Packages.props
- src/MartinCostello.BrowserStack.Automate/MartinCostello.BrowserStack.Automate.csproj
- Use Microsoft.AspNetCore.WebUtilities 2.3.0 for `netstandard2.0`.
- Bump Microsoft.AspNetCore.WebUtilities to 9.0.1 for tests.
- Ignore dependabot updates for Microsoft.AspNetCore.WebUtilities.
> Bump Microsoft.AspNetCore.WebUtilities
